// Compare two supplied files generated by index.js to determine whether
// there are any classname clashes

'use strict'

var scrape  = require('./lib/scrape')

function compare(classes1, classes2) {
    var clashes = []
    var classes2Sorted = Object.keys(classes2).sort()

    Object.keys(classes1).sort().map(function(className1, i){
        classes2Sorted.map(function(className2, j){
            if (className1 == className2) {
                clashes.push(className1)
            }
        })
    })

    return clashes
}

// expecting: node compare.js http://stuff.co.nz http://athena.fairfaxmedia.co.nz/sites/site-athena/article-page.php?sitebreakpoint=desktop&sectionname=national
var url1 = process.argv[2]
var url2 = process.argv[3]

scrape.get(url1, function(classes1){

    scrape.get(url2, function(classes2){

        var clashes = compare(classes1, classes2)

        if (clashes.length) {
            console.log('*** Clashes detected! ***\n')
            clashes.map(function(className){
                console.log(className)
            })
        } else {
            console.log('*** No clashes detected ***')
        }

    })

})
